server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # Qualquer rota do app (ex: /receitas/123) devolve o index.html para o React cuidar
  location / {
    try_files $uri $uri/ /index.html;
  }
}
